In [1]:
from fast_borf.moving import move_std, move_mean
import bottleneck as bn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from fast_borf.weighted.moving import (
    weighted_moving_standard_deviation_naive,
    weighted_running_moving_standard_deviation_naive,

    weighted_moving_average_naive,
    weighted_running_moving_average_naive,

    weighted_moving_average_textbook,
    weighted_running_moving_average_textbook,

    weighted_moving_standard_deviation_welford,
    weighted_running_moving_standard_deviation_welford
)

In [3]:
LENGTH = 10
arr = np.arange(LENGTH)
arr = np.random.rand(LENGTH)
weights = np.ones(LENGTH)
weights = np.random.rand(LENGTH)
window_width = 5

In [4]:
weighted_moving_standard_deviation_naive(arr, weights, window_width)

array([       nan,        nan,        nan,        nan, 0.23028106,
       0.15725781, 0.07535882, 0.10708695, 0.09917566, 0.18156193])

In [5]:
weighted_running_moving_standard_deviation_naive(arr, weights, window_width)

array([0.        , 0.31506977, 0.25337005, 0.24512919, 0.23028106,
       0.15725781, 0.07535882, 0.10708695, 0.09917566, 0.18156193])

In [6]:
weighted_moving_standard_deviation_welford(arr, weights, window_width)

array([       nan,        nan,        nan,        nan, 0.23028106,
       0.15725781, 0.07535882, 0.10708695, 0.09917566, 0.18156193])

In [7]:
weighted_running_moving_standard_deviation_welford(arr, weights, window_width)

array([0.        , 0.31506977, 0.25337005, 0.24512919, 0.23028106,
       0.15725781, 0.07535882, 0.10708695, 0.09917566, 0.18156193])

In [8]:
weighted_moving_average_naive(arr, weights, window_width)

array([       nan,        nan,        nan,        nan, 0.55650086,
       0.58760422, 0.47696691, 0.48815968, 0.51113045, 0.56505353])

In [9]:
weighted_running_moving_average_naive(arr, weights, window_width)

array([0.05875745, 0.6548088 , 0.59150462, 0.54811672, 0.55650086,
       0.58760422, 0.47696691, 0.48815968, 0.51113045, 0.56505353])

In [10]:
weighted_moving_average_textbook(arr, weights, window_width)

array([       nan,        nan,        nan,        nan, 0.55650086,
       0.58760422, 0.47696691, 0.48815968, 0.51113045, 0.56505353])

In [11]:
weighted_running_moving_average_textbook(arr, weights, window_width)

array([0.05875745, 0.6548088 , 0.59150462, 0.54811672, 0.55650086,
       0.58760422, 0.47696691, 0.48815968, 0.51113045, 0.56505353])