In [19]:
import numpy as np
from fast_borf.weighted.symbolic_aggregate_approximation_weighted import sax as sax_weighted
from fast_borf._deprecated.symbolic_aggregate_approximation import sax

In [65]:
arr = np.random.rand(20)
timestamps = np.arange(20) + np.random.rand(20)
window_size = 8
word_length = 2
bins = np.array([-0.67, 0, 0.67])
stride=2
dilation=2
min_window_to_signal_std_ratio=0.0

In [66]:
timestamps

array([ 0.79266988,  1.75511412,  2.72678134,  3.49727068,  4.99694323,
        5.18068731,  6.44883172,  7.5240136 ,  8.63590124,  9.92466507,
       10.99254348, 11.28894442, 12.03140825, 13.80361625, 14.86537283,
       15.76201069, 16.47809302, 17.93842272, 18.11695251, 19.43157444])

In [68]:
sax_weighted(
    arr,
    timestamps,
    window_size,
    word_length,
    bins,
    stride,
    dilation,
    min_window_to_signal_std_ratio,
)

array([[1, 2],
       [2, 1],
       [2, 1]], dtype=uint8)

In [69]:
sax(
    arr,
    window_size,
    word_length,
    bins,
    stride,
    dilation,
    min_window_to_signal_std_ratio,
)

array([[2, 1],
       [2, 1],
       [2, 1]], dtype=uint8)

In [36]:
SIZE = 100000
arr = np.random.rand(SIZE)
timestamps = np.arange(SIZE)
window_size = 80
word_length = 8
bins = np.array([-0.67, 0, 0.67])
stride=2
dilation=3
min_window_to_signal_std_ratio=0.01

In [37]:
%%timeit
sax_weighted(
    arr,
    timestamps,
    window_size,
    word_length,
    bins,
    stride,
    dilation,
    min_window_to_signal_std_ratio,
)

7.93 ms ± 115 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [38]:
%%timeit
sax(
    arr,
    window_size,
    word_length,
    bins,
    stride,
    dilation,
    min_window_to_signal_std_ratio,
)

7.19 ms ± 24 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [39]:
np.allclose(
    sax_weighted(
        arr,
        timestamps,
        window_size,
        word_length,
        bins,
        stride,
        dilation,
        min_window_to_signal_std_ratio,
    ),
    sax(
        arr,
        window_size,
        word_length,
        bins,
        stride,
        dilation,
        min_window_to_signal_std_ratio,
    ),
)

True

In [113]:
a = np.random.randn(3, 3)
a[0, 0] = np.nan
a

array([[        nan,  0.24994081, -0.51119246],
       [-1.43426008,  2.2376831 , -0.45994756],
       [-0.2128068 ,  1.00489519, -2.24097401]])

In [114]:
b = np.asarray(a)
b = b[~np.isnan(b)]
b

array([ 0.24994081, -0.51119246, -1.43426008,  2.2376831 , -0.45994756,
       -0.2128068 ,  1.00489519, -2.24097401])

In [115]:
a

array([[        nan,  0.24994081, -0.51119246],
       [-1.43426008,  2.2376831 , -0.45994756],
       [-0.2128068 ,  1.00489519, -2.24097401]])